version: "3.9"
services:
  my-app:
    image: mandarin-flashcard-application
    environment:
      - MONGO_DATABASE=mandarinDatabase
      - MONGO_USER=lioneltlynch
      - MONGO_PASSWORD=Lionel2324
      - MONGO_CLUSTER=cluster0.ij7tcyu.mongodb.net
    ports:
      - "8080:8080"
    networks:
      my-network:
        ipv4_address: 172.16.238.10
networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24