version: "3.9"
services:
  my-app:
    image: mandarin-flashcard-application
    ports:
      - "8080:8080"
    networks:
      my-network:
        ipv4_address: 172.16.238.10
networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24